/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicPlayer_apiPhpRouteImport } from './routes/api/public/player_api/php'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlayer_apiPhpRoute = ApiPublicPlayer_apiPhpRouteImport.update({
  id: '/api/public/player_api/php',
  path: '/api/public/player_api/php',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/player_api/php': typeof ApiPublicPlayer_apiPhpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/player_api/php': typeof ApiPublicPlayer_apiPhpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/player_api/php': typeof ApiPublicPlayer_apiPhpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/player_api/php'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/player_api/php'
  id: '__root__' | '/' | '/api/public/player_api/php'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicPlayer_apiPhpRoute: typeof ApiPublicPlayer_apiPhpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/player_api/php': {
      id: '/api/public/player_api/php'
      path: '/api/public/player_api/php'
      fullPath: '/api/public/player_api/php'
      preLoaderRoute: typeof ApiPublicPlayer_apiPhpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicPlayer_apiPhpRoute: ApiPublicPlayer_apiPhpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
