CREATE TABLE public.custom_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  enabled BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE public.custom_category_streams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  custom_category_id BIGINT NOT NULL REFERENCES public.custom_categories(id) ON DELETE CASCADE,
  stream_upstream_id TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(custom_category_id, stream_upstream_id)
);

ALTER TABLE public.custom_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.custom_category_streams ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated users full access" ON public.custom_categories FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow authenticated users full access" ON public.custom_category_streams FOR ALL TO authenticated USING (true);
