ALTER TABLE public.app_settings
  ADD COLUMN IF NOT EXISTS sync_auto_live BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS sync_auto_vod BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS sync_auto_series BOOLEAN NOT NULL DEFAULT true;