CREATE TABLE public.app_settings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  xtream_host TEXT,
  xtream_username TEXT,
  xtream_password TEXT,
  proxy_username TEXT,
  proxy_password TEXT,
  sync_interval_live_minutes INTEGER DEFAULT 60,
  sync_interval_vod_minutes INTEGER DEFAULT 1440,
  sync_interval_series_minutes INTEGER DEFAULT 1440,
  last_sync_live_at TIMESTAMP WITH TIME ZONE,
  last_sync_vod_at TIMESTAMP WITH TIME ZONE,
  last_sync_series_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert a default row so settings operations work
INSERT INTO public.app_settings (xtream_host) VALUES ('');

CREATE TABLE public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  upstream_id TEXT NOT NULL,
  type TEXT NOT NULL,
  name TEXT,
  parent_id TEXT,
  enabled BOOLEAN DEFAULT TRUE,
  UNIQUE(type, upstream_id)
);

CREATE TABLE public.live_streams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  upstream_id TEXT NOT NULL UNIQUE,
  name TEXT,
  stream_icon TEXT,
  epg_channel_id TEXT,
  added TEXT,
  category_id TEXT,
  custom_sid TEXT,
  tv_archive TEXT,
  direct_source TEXT,
  tv_archive_duration TEXT,
  num TEXT,
  raw JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE public.vod_streams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  upstream_id TEXT NOT NULL UNIQUE,
  name TEXT,
  stream_icon TEXT,
  rating TEXT,
  added TEXT,
  category_id TEXT,
  container_extension TEXT,
  custom_sid TEXT,
  direct_source TEXT,
  num TEXT,
  raw JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE public.vod_info (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vod_id TEXT NOT NULL UNIQUE,
  info JSONB,
  movie_data JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE public.series (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  upstream_id TEXT NOT NULL UNIQUE,
  name TEXT,
  cover TEXT,
  plot TEXT,
  cast_text TEXT,
  director TEXT,
  genre TEXT,
  release_date TEXT,
  last_modified TEXT,
  rating TEXT,
  category_id TEXT,
  num TEXT,
  raw JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE public.series_info (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  series_id TEXT NOT NULL UNIQUE,
  info JSONB,
  seasons JSONB,
  episodes JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE public.sync_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL,
  status TEXT NOT NULL,
  items_processed INTEGER,
  message TEXT,
  started_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  finished_at TIMESTAMP WITH TIME ZONE
);

-- Note: No RLS policies since these are backend tables accessed via supabaseAdmin
-- However, we must enable RLS on app_settings just in case it's ever queried by anon
ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.live_streams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vod_streams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vod_info ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.series ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.series_info ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sync_runs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated users full access" ON public.app_settings FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow authenticated users full access" ON public.categories FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow authenticated users full access" ON public.live_streams FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow authenticated users full access" ON public.vod_streams FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow authenticated users full access" ON public.vod_info FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow authenticated users full access" ON public.series FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow authenticated users full access" ON public.series_info FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow authenticated users full access" ON public.sync_runs FOR ALL TO authenticated USING (true);
